services:
  - type: web
    name: servidor-transcricao
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: OPENAI_API_KEY
        value: sua_chave_aqui
    region: oregon
